### ISSUE TITLE
error & crash

### ISSUE THREAD

**Issue by TheFaik** [PurpurMC/PurpurClient#34]
[Render thread/ERROR]:
 Reported exception thrown!
net.minecraft.class_148: Ticking entity
	at net.minecraft.class_1937.method_18472(class_1937.java:499) ~[client-intermediary.jar:?]
	at net.minecraft.class_638.method_32124(class_638.java:260) ~[client-intermediary.jar:?]
	at net.minecraft.class_5574.method_31791(class_5574.java:54) ~[client-intermediary.jar:?]
	at net.minecraft.class_638.method_18116(class_638.java:256) ~[client-intermediary.jar:?]
	at net.minecraft.class_310.method_1574(class_310.java:2011) ~[client-intermediary.jar:?]
	at net.minecraft.class_310.method_1523(class_310.java:1289) ~[client-intermediary.jar:?]
	at net.minecraft.class_310.method_1514(class_310.java:888) ~[client-intermediary.jar:?]
	at net.minecraft.client.main.Main.main(Main.java:265) ~[1.20.4-0.15.3.jar:?]
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:470) ~[fabric-loader-0.15.3.jar:?]
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74) ~[fabric-loader-0.15.3.jar:?]
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23) ~[fabric-loader-0.15.3.jar:?]
Caused by: java.lang.RuntimeException: Mixin transformation of net.minecraft.class_1890 failed
	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.getPostMixinClassByteArray(KnotClassDelegate.java:427) ~[fabric-loader-0.15.3.jar:?]
	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.tryLoadClass(KnotClassDelegate.java:323) ~[fabric-loader-0.15.3.jar:?]
	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.loadClass(KnotClassDelegate.java:218) ~[fabric-loader-0.15.3.jar:?]
	at net.fabricmc.loader.impl.launch.knot.KnotClassLoader.loadClass(KnotClassLoader.java:119) ~[fabric-loader-0.15.3.jar:?]
	at java.lang.ClassLoader.loadClass(Unknown Source) ~[?:?]
	at net.minecraft.class_746.method_6007(class_746.java:703) ~[client-intermediary.jar:?]
	at net.minecraft.class_1309.method_5773(class_1309.java:2446) ~[client-intermediary.jar:?]
	at net.minecraft.class_1657.method_5773(class_1657.java:284) ~[client-intermediary.jar:?]
	at net.minecraft.class_742.method_5773(class_742.java:59) ~[client-intermediary.jar:?]
	at net.minecraft.class_746.method_5773(class_746.java:218) ~[client-intermediary.jar:?]
	at net.minecraft.class_638.method_18646(class_638.java:1184) ~[client-intermediary.jar:?]
	at net.minecraft.class_1937.method_18472(class_1937.java:492) ~[client-intermediary.jar:?]
	... 10 more

**Comment by granny** [comment]
This doesn't really tell me anything. Can you share your whole log file where the error occurred by uploading to https://mclo.gs/ and sending the generated link here? You could also join our discord and ask for more help in the #support channel; https://purpurmc.org/discord

**Comment by granny** [comment]
Stale issue
